# Generated by Django 5.1 on 2024-09-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asgns', '0002_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
            ],
        ),
    ]
