# Generated by Django 5.1 on 2024-09-27 18:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('DSAI', 'Data Science and Artificial Intelligence'), ('MNC', 'Mathematics and Computing'), ('ECE', 'Electronics and Communication'), ('EE', 'Electrical'), ('ME', 'Mechanical'), ('PNI', 'Production and Industrial'), ('MT', 'Metallurgy'), ('BSBE', 'Biosciences and Biotechnology'), ('BSCS', 'Chemical Sciences')], default='CSE', max_length=5)),
                ('enrollment_number', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_session', to='asgns.academic_session')),
                ('user_and_academic_session', models.ManyToManyField(to='asgns.academic_session')),
            ],
        ),
    ]
