# Generated by Django 5.1 on 2024-10-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0011_alter_assignment_assigner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='iteration_no',
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateTimeField(null=True),
        ),
    ]
