# Generated by Django 5.1 on 2024-10-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0012_remove_submission_iteration_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academic_session',
            field=models.ManyToManyField(related_name='acad_session_of_user', to='asgns.academic_session'),
        ),
    ]
