# Generated by Django 5.1 on 2024-11-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0014_administrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
