# Generated by Django 5.1 on 2024-11-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0015_remove_user_username_alter_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
