# Generated by Django 5.1 on 2024-11-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0017_alter_user_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='academic_session',
        ),
        migrations.DeleteModel(
            name='Academic_session',
        ),
    ]
