# Generated by Django 5.1 on 2024-12-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0020_remove_assignment_asgn_allocated_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='title',
        ),
    ]
