# Generated by Django 5.1 on 2024-12-12 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0021_remove_assignment_text_remove_subtask_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='enrollment_number',
            field=models.CharField(default='2311', max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$216000$Y9O8na7mFa0f$Tmygtvg6xZPaq82A+bxkDmI5j65M43FbWhVwdB/Zs4w=', max_length=128),
            preserve_default=False,
        ),
    ]
