# Generated by Django 5.1 on 2024-12-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0022_alter_user_options_alter_user_enrollment_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='image',
        ),
    ]
