# Generated by Django 5.1 on 2024-12-18 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0023_remove_attachment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment_allocated_to',
            name='user',
        ),
        migrations.AddField(
            model_name='assignment_allocated_to',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='assigned_assignments', to='asgns.team'),
        ),
        migrations.AddField(
            model_name='assignment_allocated_to',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='assigned_assignments', to='asgns.user'),
        ),
        migrations.AlterField(
            model_name='assignment_allocated_to',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='asgns.assignment'),
        ),
    ]
