# Generated by Django 5.1 on 2024-12-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0024_remove_assignment_allocated_to_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment_allocated_to',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='assignment_allocated_to',
            name='users',
        ),
        migrations.AddField(
            model_name='assignment_allocated_to',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_assignments', to='asgns.team'),
        ),
        migrations.AddField(
            model_name='assignment_allocated_to',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_assignments', to='asgns.user'),
        ),
    ]
