# Generated by Django 5.1 on 2024-12-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0026_alter_user_options_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$VetGjS4kYJVe3x520IhbAd$D/vv5RXOIXoOnUQNxplKicOh8Us+mriGtHahSqk0d94=', max_length=128),
        ),
    ]
