# Generated by Django 5.1 on 2024-12-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0027_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_allocated_to',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$IwdJZi0ZjMK8Co8hZqA9X1$i4Xi1T/u01qkUnTxorUpif+WeapCv82aMWjTQtM/cRA=', max_length=128),
        ),
    ]
