# Generated by Django 5.1 on 2024-12-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0030_submission_reviewer_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Zy0xWTJTijKKMEPUwSRt11$CtQV9sXALLD5cDy7RNZxDWT05ahQzj8RVWAue9NjrZA=', max_length=128),
        ),
        migrations.DeleteModel(
            name='Completed_Assignment',
        ),
    ]
