# Generated by Django 5.1 on 2024-12-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0031_alter_user_password_delete_completed_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$w9bEAR7FxL78S0CV5Hlmwd$HrBsKoEtrKKi6RzCCO6q+AZanaU0aAgn+YplTKm25i4=', max_length=128),
        ),
    ]
