# Generated by Django 5.1 on 2024-12-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0032_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$LfxVvLHnoeAwyvarU9W2gO$SaE8YIf8ieJuIp8lpbLShDWOdN+nNpYPsRgg2fkngn0=', max_length=128),
        ),
    ]
