# Generated by Django 5.1 on 2024-12-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0034_remove_attachment_for_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$sCLNeMROgs4YnohHds2lWB$RDillQ5AL/tcd5a9eWnSJHUcIqfr0+XkPEcxsu+IwHg=', max_length=128),
        ),
    ]
