# Generated by Django 5.1 on 2024-12-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0035_submission_checked_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='iteration_no',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$JymtmT5WPBhIoXrmMBNwv7$5//zQj4PSKM1USmqCtoJnLDi8NXHAz6EyU+5kAJ3dvQ=', max_length=128),
        ),
    ]
