# Generated by Django 5.1 on 2024-12-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0036_remove_review_assignment_remove_review_iteration_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Ys7qE0Q5XNTGgUj9t1o5iN$CS8W9/8bZChag8CyR3/2R9HDuCgBXITfkiz4KfEvuqc=', max_length=128),
        ),
    ]
