# Generated by Django 5.1 on 2024-12-24 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0037_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_submissions', to='asgns.team'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='asgns.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$7HLU53Iekpd4hOuphi3GuZ$DdzmuAkkK97MK7nIxzrwNHViaoEi+v8NZWXN+L4kXaM=', max_length=128),
        ),
    ]
