# Generated by Django 5.1 on 2024-12-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0038_submission_team_alter_submission_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$emiMNrJ22VX0t4Cswz8Npv$hks21BAEH7R54SGApF9UBbi2goiJD+mJorzpymTzTxk=', max_length=128),
        ),
    ]
