# Generated by Django 5.1 on 2024-12-24 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0039_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(help_text='The user making the submission, either for themselves or on behalf of a team.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='asgns.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$mp9tistKnZzHFwAX9Zr9pn$5eGi5XOU0FyhXd/YSMy5aWe5QUKwo043ph78LWyje/g=', max_length=128),
        ),
    ]
