# Generated by Django 5.1 on 2024-12-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgns', '0040_alter_submission_user_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$AmOvsBFf3iwFpVj7d6qRT1$WD9eZ5RcJifUk6cwSJS8i2OElVv7TazzEaPgvFL65jA=', max_length=128),
        ),
    ]
